services:
  postgres-users:
    image: postgres:16-alpine
    container_name: marketplace-users-db
    environment:
      POSTGRES_DB: marketplace_users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_users:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketplace_users_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-listings:
    image: postgres:16-alpine
    container_name: marketplace-listings-db
    environment:
      POSTGRES_DB: marketplace_listings_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata_listings:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketplace_listings_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-chats:
    image: postgres:16-alpine
    container_name: marketplace-chats-db
    environment:
      POSTGRES_DB: marketplace_chats_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata_chats:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d marketplace_chats_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: marketplace-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: marketplace-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 5

  image-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=image-service
    container_name: marketplace-image-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-listings:5432/marketplace_listings_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      # ФИКС ОШИБКИ 500: Явно связываем Спринг с бакетами MinIO
      - MINIO_BUCKETS_RAW=raw-images
      - MINIO_BUCKETS_PROCESSED=market-images
    depends_on:
      postgres-listings:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=user-service
    container_name: marketplace-user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-users:5432/marketplace_users_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      postgres-users:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  listing-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=listing-service
    container_name: marketplace-listing-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-listings:5432/marketplace_listings_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      postgres-listings:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=gateway-service
    container_name: marketplace-gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - listing-service

  chat-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=chat-service
    container_name: marketplace-chat-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-chats:5432/marketplace_chats_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      postgres-chats:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notification-service:
    build:
      context: .                  # Переключаем на корень проекта
      dockerfile: Dockerfile      # Используем общий Dockerfile
      args:
        - SERVICE_NAME=notification-service
    container_name: marketplace-notification-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      rabbitmq:
        condition: service_healthy # Ждем, пока Кролик залогирует ping

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: marketplace-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - gateway-service

volumes:
  pgdata_users:
  pgdata_listings:
  pgdata_chats:
  minio_data: