version: '3.8'

services:
  postgres-users:
    image: postgres:16-alpine
    container_name: marketplace-users-db
    environment:
      POSTGRES_DB: marketplace_users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_users:/var/lib/postgresql/data
    # Проверка готовности базы данных
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketplace_users_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=user-service
    container_name: marketplace-user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-users:5432/marketplace_users_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      postgres-users:
        condition: service_healthy

  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=gateway-service
    container_name: marketplace-gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - user-service

volumes:
  pgdata_users: