server:
  port: 8082

spring:
  application:
    name: listing-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/marketplace_listings_db}
    username: ${SPRING_DATASOURCE_PASSWORD:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: marketplace-rabbitmq
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true