server:
  port: 8085

spring:
  application:
    name: chat-service

  datasource:
    url: jdbc:postgresql://postgres-chats:5432/marketplace_chats_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect